<?php session_start(); ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Job Candidates</title>
    <link rel="stylesheet"
          href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css"/>
   <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrapValidator.min.css"/> 
</head>
<body>
   

