<?php session_start(); ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Новините днес</title>
    <link rel="stylesheet"
          href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css"/>
   <link rel="stylesheet" href="<?php echo WEB_ROOT ?>/extend_libraries/bootstrap-3.3.7-dist/css/bootstrapValidator.min.css"/>       
    <script src="<?php echo WEB_ROOT ?>/js/news_today_table.js"></script>  
</head>
<body>
    